### ISSUE TITLE
Few concerns for CMakeLists.txt about compiler flags

### ISSUE THREAD

**Issue by saki7** [zussel/oos#75]
- Add `-O3` to the Release configuration to be more explicit
  - Make sure `-O3` is removed and `-O0` is added to the Debug configuration
  - In addition to the basic common configuration (which is `CMAKE_CXX_FLAGS`), you can use `set(CMAKE_CXX_FLAGS_DEBUG "-DDEBUG -g -O0")` `set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG -O3")` for this
- Specifying both `-std=c++11` and `-std=gnu++11` has no effect (either one will be chosen)
  - We should stick to `-std=c++14` for conforming to the current standard and disabling unnecessary GNU extensions
- We need to specify optimization flags for VC++ too
  - Sorry but I don't have much knowledge about them

**Comment by zussel** [comment]
These are indeed good points. I'll fix them before release. But I must admit also less knowledge on VC++ compiler options. I have to dig into it (a bit at least).

Right now I'm preparing the documentation for release. Hope I get it done over xmas.

For future release I want travis and appveyor to build and upload the packages to github. That would ease the release process.

**Comment by saki7** [comment]
> Right now I'm preparing the documentation for release. Hope I get it done over xmas.

Nice! But for Xmas enjoy & have a nice party with your family! 😄 🎄 

I feel a bit sorry but I'm gonna be a bit off-topic here since right now there's no where else to talk...

If my memory is correct you have said that you were planning to release Floian by the end of year but I think we can loosen the release date till the middle of January.

We have few major tickets remaining such as #67: a huge security issue and #71: great help for newcomers. And also #68 is important and I think it should be done *just before* the release. Because people might come for questions.

So IMO there's at least 3 + 1 (this) tickets remaining for Floian.

And for the future release schedule I think we can omit 0.5.x and go for 0.6.0 because many of the existing tickets add a major feature or break the API. But if we find any security issues in 0.6.0 we can backport them into 0.5.1+ (which would be an official patchlevel release for the 0.5.0 series).

> For future release I want travis and appveyor to build and upload the packages to github. That would ease the release process.

And this is indeed much better.

**Comment by saki7** [comment]
And if you need any help, feel free to contact me any time.
It's still hard for me to implement core-related features such as the API breaking ones but I can help you with lighter ones like #64

**Comment by zussel** [comment]
> Nice! But for Xmas enjoy & have a nice party with your family! :smile: :christmas_tree:

I wish the same to you and your family. Last friday our family has grown: We welcomed _Blacky_ our new dog :smile: Kids are happy!

> I feel a bit sorry but I'm gonna be a bit off-topic here since right now there's no where else to talk...

We could do that kind of talk via email. Just write me a mail to _oos at zussel dot de_ and I'll answer with my private email. What do you think?

It was my intent to release Floian by the end of year because it is in a stable condition and for a 0.5 version feature complete and last but not least it is almost three year since the last release.

But indeed the issues you mentioned will make the library more secure and gives the user a good starting point at hand.

So I'll consider your suggestion! With the example project we can't do all we want in this project because we didn't have ```belongs_to``` and ```many_to_many```. But I think we can somehow omit it.

> And if you need any help, feel free to contact me any time.

Thank you for that! That helps.

I think the quoting and escaping of string literals is kind of core but I won't hold you back to take at least a look into it. The build up of the statements is done in ```basic_dialect_linker()``` and the ```condition``` classes.

But also the unified connection string parser is an issue (not urgent but reasonable).

Or the auto upload for travis and appveyor.

You see if you want to support feel free to pick something :smile:

**Comment by saki7** [comment]
VC++ CL memo
- /O2≒-O2 (/O2 is preferred over /Ox)
- /Od≒-O0
- /-Zi≒-g (/-Zi is preferred over /Z7)
- /Wall≒-Wall + -Wextra
- /std:c++14≒-std=c++14

**Comment by saki7** [comment]
Ooops those are for rebasing and removing merge commits

**Comment by zussel** [comment]
Ok, I've a VM where I can take a look onto these compiler options. That are indeed a lot of complains.

> Ooops those are for rebasing and removing merge commits

What do you mean with that?

**Comment by saki7** [comment]
I mean there are three same merged commits shown on my machine :( never mind...

**Comment by zussel** [comment]
Fixed with #77
